# Generated by Django 2.0 on 2017-12-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_by_image',
            field=models.CharField(max_length=255),
        ),
    ]
